name: "whatsapp"
dependencies: []
config:
  install_type: "deb"
  install_url: "https://github.com/enesbcs/whatsapp-for-linux/releases/download/v1.1.0/whatsapp-for-linux_amd64.deb"
  install_path: "/tmp/whatsapp.deb"
  check_installed: "dpkg -l | grep -q 'whatsapp-for-linux'"
  get_installed_version: "dpkg -l | grep whatsapp-for-linux | awk '{print $3}'"
pre_install: "echo 'Preparing to install WhatsApp...'"
post_install: "echo 'WhatsApp installation completed.'"
override_install: false