# User settings
user:
  username: "pimentel"
  home_directory: "/home/pimentel"

# System settings
system:
  preferred_shell: "zsh"

# Path settings
paths:
  dotfiles_directory: "/home/pimentel/.dotfiles"
  log_file: "/home/pimentel/.dotfiles/install.log"

apps:
  - bash
  - python
  - git
  - streamio
