# User settings
user:
  username: "pimentel"
  home_directory: "/home/pimentel"
  name: "Felipe Pimentel"
  email: "fpimentel88@gmail.com"

# System settings
system:
  preferred_shell: "zsh"

# Path settings
paths:
  dotfiles_directory: "/home/pimentel/.dotfiles"
  log_file: "/home/pimentel/.dotfiles/install.log"
  vault_directory: "/home/pimentel/ObsidianVault"
  desktop_directory: "/home/pimentel/.local/share/applications"

# Applications and tools settings
tools:
  apps:
    - zsh
    - git
    - vscode
    - python
    - poetry
    - docker
    - vim
    - figma
    - inkscape
    - gimp

# Security settings
security:
  tool: "1pass"
