# User settings
user:
  username: "pimentel"
  home_directory: "/home/pimentel"

# System settings
system:
  preferred_shell: "zsh"
  package_manager: "apt"

# Path settings
paths:
  dotfiles_directory: "/home/pimentel/.dotfiles"
  log_file: "/home/pimentel/.dotfiles/install.log"

apps:
  - brew
  - bash
  - python