name: "edge"
dependencies:
  - "curl"
  - "gpg"
config:
  install_type: "apt"
  repo_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
  repo_entry: "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
  package_name: "microsoft-edge-stable"
  check_installed: "dpkg -l | grep -q microsoft-edge-stable"
  get_installed_version: "microsoft-edge --version | awk '{print $3}'"
pre_install: |
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
  rm microsoft.gpg
post_install: "echo 'Microsoft Edge installation completed.'"
override_install: false