name: "warp"
dependencies:
  - "wget"
  - "dpkg"
config:
  install_type: "deb"
  install_url: "https://app.warp.dev/download?package=deb"
  install_command: |
    wget -O /tmp/warp.deb "https://app.warp.dev/download?package=deb" && \
    sudo dpkg -i /tmp/warp.deb && \
    sudo apt-get install -f -y
  check_installed: "[ -x $(command -v warp) ]"
  get_installed_version: "warp --version | awk '{print $3}' || echo 'Not installed'"
  icon_url: "https://warp.dev/static/favicon/favicon.ico"
  desktop_entry:
    name: "Warp Terminal"
    comment: "Warp is a modern terminal for developers."
    exec: "warp"
    categories: "Utility;TerminalEmulator;"
    startup_wm_class: "Warp"
pre_install: "echo 'Preparing to install Warp Terminal...'"
post_install: "echo 'Warp Terminal installation completed.'"
override_install: false
