name: "vscode"
dependencies: []
config:
  install_type: "apt"
  package_name: "code"
  check_installed: "command -v code &> /dev/null"
  get_installed_version: "code --version | head -n 1"
  theme: "Dark+"
  font_family: "Fira Code"
  font_size: 14
pre_install: |
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
  sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
  rm -f packages.microsoft.gpg
post_install: "echo 'VS Code installation completed.'"
override_install: false
