name: "git"
dependencies:
  - "git"
  - "software-properties-common"
config:
  install_type: "apt"
  package_name: "git gh"
  check_installed: "command -v git &> /dev/null && command -v gh &> /dev/null"
  get_installed_version: "git --version | awk '{print $3}'"
pre_install: |
  sudo apt-get install -y software-properties-common
  sudo add-apt-repository -y ppa:git-core/ppa
override_install: false
config_files:
  .gitconfig: "~/.gitconfig"