# apps/python/config.yml
name: "python"
dependencies: []
config:
  install_type: "apt"
  package_name: "python3 python3-pip python3-venv"
  check_installed: "command -v python3 &> /dev/null"
  get_installed_version: "python3 --version | awk '{print $2}'"
pre_install: "echo 'Preparando para instalar Python e Poetry...'"
post_install: |
  # Instalação do Poetry
  echo 'Instalando Poetry...'
  curl -sSL https://install.python-poetry.org | python3 -

  # Exportando variáveis de ambiente do Poetry
  export POETRY_SHELL=zsh
  export PATH="$HOME/.poetry/bin:$PATH"
  echo 'Instalação do Poetry concluída.'
override_install: false
